# mock_data.py

MOCK_INSTAGRAM_POSTS = [
    {
        "ig_post_id": "3623582459620599999",
        "description": "Heavy Rain at Penang Island 252025 7pm #penang #flood",
        "cleaned_description": "Heavy Rain at Penang Island 252025 7pm",
        "hashtags": "penang, rain, raining, flood",
        "author_username": "penang_weather_watch",
        "author_full_name": "Penang Watcher",
        "address": "persiaran karpal singh",
        "city": "george town, malaysia",
        "location_name": "karpal singh drive,penang",
        "latitude": 5.3978358790044,
        "longitude": 100.32904171891,
        "is_verified": False,
        "reported_as_spam": False,
        "gen_ai_detection_method": "NONE",
        "integrity_review_decision": "pending"
    },
    {
        "ig_post_id": "3623582459620582548",
        "description": "Flash floods reported in Shah Alam Seksyen 13. Stay safe everyone! #shahalam #banjir",
        "cleaned_description": "Flash floods reported in Shah Alam Seksyen 13. Stay safe everyone!",
        "hashtags": "shahalam, banjir, selangor",
        "author_username": "selangor_updates",
        "author_full_name": "Selangor News",
        "address": "Seksyen 13",
        "city": "Shah Alam, Malaysia",
        "location_name": "Stadium Shah Alam",
        "latitude": 3.0705,
        "longitude": 101.5431,
        "is_verified": True,
        "reported_as_spam": False,
        "gen_ai_detection_method": "NONE",
        "integrity_review_decision": "pending"
    },
    {
        "ig_post_id": "3623582459620582549",
        "description": "Landslide near Karak Highway. Traffic is at a standstill. #karak #landslide",
        "cleaned_description": "Landslide near Karak Highway. Traffic is at a standstill.",
        "hashtags": "karak, landslide, traffic",
        "author_username": "highway_traveler",
        "author_full_name": "Traveler MY",
        "address": "Karak Highway",
        "city": "Bentong, Malaysia",
        "location_name": "Genting Sempah",
        "latitude": 3.3492,
        "longitude": 101.7850,
        "is_verified": False,
        "reported_as_spam": False,
        "gen_ai_detection_method": "NONE",
        "integrity_review_decision": "pending"
    },
    {
        "ig_post_id": "3623582459620582550",
        "description": "Water level in Sungai Muda is rising dangerously. Resident alert! #kedah #flood",
        "cleaned_description": "Water level in Sungai Muda is rising dangerously. Resident alert!",
        "hashtags": "kedah, sungai, alert",
        "author_username": "kedah_citizen",
        "author_full_name": "Kedah Info",
        "address": "Sungai Muda",
        "city": "Alor Setar, Malaysia",
        "location_name": "Jambatan Merdeka",
        "latitude": 5.5786,
        "longitude": 100.4182,
        "is_verified": False,
        "reported_as_spam": False,
        "gen_ai_detection_method": "NONE",
        "integrity_review_decision": "pending"
    },
    {
        "ig_post_id": "3623582459620582551",
        "description": "Storm hitting Kota Kinabalu waterfront. High winds and heavy rain. #sabah #storm",
        "cleaned_description": "Storm hitting Kota Kinabalu waterfront. High winds and heavy rain.",
        "hashtags": "sabah, storm, weather",
        "author_username": "sabah_vibe",
        "author_full_name": "Sabah Daily",
        "address": "KK Waterfront",
        "city": "Kota Kinabalu, Malaysia",
        "location_name": "Jalan Tun Fuad Stephens",
        "latitude": 5.9804,
        "longitude": 116.0735,
        "is_verified": True,
        "reported_as_spam": False,
        "gen_ai_detection_method": "NONE",
        "integrity_review_decision": "pending"
    },
    {
        "ig_post_id": "3623582459620582552",
        "description": "Wildfire reported near Miri. Haze levels are rising, please wear masks! #sarawak #wildfire #haze",
        "cleaned_description": "Wildfire reported near Miri. Haze levels are rising, please wear masks!",
        "hashtags": "sarawak, wildfire, haze, miri",
        "author_username": "borneo_alert",
        "author_full_name": "Borneo News Network",
        "address": "Kuala Baram",
        "city": "Miri, Sarawak",
        "location_name": "Kuala Baram Industrial Estate",
        "latitude": 4.5886,
        "longitude": 114.1255,
        "is_verified": True,
        "reported_as_spam": False,
        "gen_ai_detection_method": "NONE",
        "integrity_review_decision": "pending"
    }
]