FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    build-essential gcc g++ python3-dev libffi-dev \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONUNBUFFERED=1
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN mkdir -p /app/data

# This is a base command; docker-compose will override it
CMD ["python", "-u", "core/consumers/incident_worker.py"]