from typing import Literal
from pydantic import BaseModel, Field

# FR-019: The eight required disaster categories + 'none'
DisasterType = Literal[
    "flood", 
    "landslide", 
    "storm", 
    "haze", 
    "forest fire", 
    "earthquake", 
    "sinkhole", 
    "tsunami",
    "none"
]

class IncidentClassificationOutput(BaseModel):
    """Schema for the LLM's structured incident classification output."""
    
    # FR-021: Classification label
    classification_type: DisasterType = Field(
        ..., 
        description="The primary disaster type for the post, chosen from the predefined list. Use 'none' if irrelevant."
    )
    # Confidence score 0.0-1.0
    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence score for the classification (0.0 to 1.0)."
    )

 # Define the schema for the single-topic extraction (Phase 1 of Trend Analysis)
class TopicExtractionOutput(BaseModel):
    """Schema for the LLM's structured output for Phase 1: Topic Extraction."""
    
    # The string generated by the AI (e.g., 'flood in johor')
    main_topic: str = Field(
        ...,
        description="The SINGLE most important event and location, max 5 words. Example: 'Flood in Johor'."
    )

# Define the schema for the sentiment classification output
class SentimentOutput(BaseModel):
    """Schema for disaster sentiment classification."""
    reasoning: str = Field(description="Reasoning based on disaster urgency.")
    sentiment_label: Literal["Urgent", "Warning", "Informational"] = Field(
        validation_alias='sentiment',
        description="Urgent: Life threatening. Warning: Caution needed. Informational: General news."
    )
    confidence_score: float = Field(description="Confidence level between 0.0 and 1.0.")

# Define the schema for location extraction
class LocationExtraction(BaseModel):
    """
    Schema for OpenAI to extract location intent from unstructured text.
    """
    state: str = Field(
        ..., 
        description="The official Malaysian state name (e.g., Selangor, Sarawak)."
    )
    district: str = Field(
        ..., 
        description="The specific district or area mentioned (e.g., Klang, Matang)."
    )
    search_string: str = Field(
        ..., 
        description="A clean, optimized string for OpenCage geocoding (e.g., 'Matang, Sarawak')."
    )
    reasoning: str = Field(
        ..., 
        description="A short explanation of why this location was chosen from the text."
    )
       