# backend/jobs/trend_schemas.py
from pydantic import BaseModel, Field

# Define the schema for the single-topic extraction (Phase 1 of Trend Analysis)
class TopicExtractionOutput(BaseModel):
    """Schema for the LLM's structured output for Phase 1: Topic Extraction."""
    
    # The string generated by the AI (e.g., 'flood in johor')
    main_topic: str = Field(
        ...,
        description="The SINGLE most important event and location, max 5 words. Example: 'Flood in Johor'."
    )
    
# --- Sentiment Analysis Schema (Placeholder until friend provides full details) ---
# NOTE: This is required if your friend's code uses structured output.
class SentimentAnalysisOutput(BaseModel):
    sentiment_label: str = Field(..., description="The classified sentiment: 'positive', 'negative', or 'neutral'.")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Confidence score for the sentiment.")

    