name: Run Tweet Scraper Hourly

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour (temporarily stop)
  workflow_dispatch: # Allow manual trigger too

jobs:
  run-script:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache NLTK data
        uses: actions/cache@v3
        with:
          path: ~/.cache/nltk
          key: ${{ runner.os }}-nltk

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm
          python -m nltk.downloader stopwords

      - name: Run scraper
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          RAPIDAPI_HOST: ${{ secrets.RAPIDAPI_HOST }}
        run: python TweetDataScraper/main.py
